---
# tasks to create App Stack
- name: "test-sg"
  resource: "test-sg"
  group: "test"
  type: "infrastructure"
  account: "unison-np"
  environment: "np"
  configuration: "test-sg-np"
  steps:
    - name: "deploy cfn"
      type: "cloudformation"
      action_script: "deploy_cfn.sh"
      action_template: "cfn.yml"
    - name: "status"
      type: "shell"
      action_script: "status.sh"

- name: "test-sg2"
  resource: "test-sg2"
  group: "test"
  type: "infrastructure"
  account: "unison-np"
  environment: "np"
  configuration: "test-sg2-np"
  steps:
    - name: "deploy cfn"
      type: "cloudformation"
      action_script: "deploy_cfn.sh"
      action_template: "cfn.yml"
    - name: "status"
      type: "shell"
      action_script: "status.sh"

#- name: "test-ec2"
#  resource: "test-ec2"
#  group: "test"
#  type: "infrastructure"
#  account: "unison-np"
#  environment: "np"
#  configuration: "test-ec2-np"
#  steps:
#    - name: "deploy cfn"
#      type: "cloudformation"
#      action_script: "deploy_cfn.sh"
#      action_template: "cfn.yml"
#    - name: "status"
#      action_script: "shell"
#      action: "status"
#
#- name: "test-s3"
#  resource: "test-s3"
#  group: "test"
#  type: "infrastructure"
#  account: "unison-np"
#  environment: "np"
#  configuration: "test-s3-np"
#  steps:
#    - name: "deploy cfn"
#      type: "cloudformation"
#      action_script: "deploy_cfn.sh"
#      action_template: "cfn.yml"
#    - name: "status"
#      type: "shell"
#      action_script: "status"