---
ec2_name: "my-test-ec2"
instance_type: "t3.small"
instance_ami: "!Sub \"{{resolve:ssm:/golden-ami/rhel8/latest}}\""
subnet_id: "{{ tooling_subnet_2 }}"
user_data: |
        #!/bin/bash -xe
        exec >> /var/log/user-data.log 2>&1
        echo BEGIN
        date '+%Y-%m-%d %H:%M:%S'
        echo "Setting up environment {{ environment }} in {{ aws_region }}"
        export no_proxy=$no_proxy,s3.ap-southeast-2.amazonaws.com
